server.port=${SERVER_PORT}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.database=${REDIS_DB}
spring.data.redis.timeout=2000

app.session.cookie-name=X-Session-Id
app.session.ttl-seconds=${APP_USER_SESSION_TTL}
app.session.prefix=sid: