server.port=${APP_PORT}

# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.database=${REDIS_DB}
spring.data.redis.timeout=2000

# MongoDB
spring.data.mongodb.host=${MONGODB_HOST}
spring.data.mongodb.port=${MONGODB_PORT}
spring.data.mongodb.database=${MONGODB_DATABASE}
spring.data.mongodb.username=${MONGODB_USER}
spring.data.mongodb.password=${MONGODB_PASSWORD}
spring.data.mongodb.auto-index-creation=true

# Cassandra
spring.cassandra.contact-points=${CASSANDRA_HOSTS}
spring.cassandra.port=${CASSANDRA_PORT}
spring.cassandra.keyspace-name=${CASSANDRA_KEYSPACE}
spring.cassandra.local-datacenter=${CASSANDRA_LOCAL_DATACENTER}

# Cookie
app.session.cookie-name=X-Session-Id
app.session.ttl-seconds=${APP_USER_SESSION_TTL}
app.session.key_prefix=sid:

# Like cache
app.like.ttl-seconds=${APP_LIKE_TTL}

# Review cache
app.review.ttl-seconds=${APP_EVENT_REVIEWS_TTL}

# Logger
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.springframework.data.redis=DEBUG
logging.level.org.springframework.data.cassandra=DEBUG